# Generated by Django 3.1.4 on 2020-12-08 18:31

from django.db import migrations, models
import django.db.models.deletion
import mvp.accounts.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID do usuário')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('is_superuser', models.BooleanField(default=True, verbose_name='administrador')),
                ('is_staff', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', mvp.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.user')),
                ('phone', models.CharField(max_length=14, unique=True, verbose_name='telefone')),
            ],
            options={
                'verbose_name': 'Anunciante',
                'verbose_name_plural': 'Anunciantes',
            },
            bases=('accounts.user',),
            managers=[
                ('objects', mvp.accounts.models.UserManager()),
            ],
        ),
    ]
